# docker-compose up -d

version: "3.8"

volumes:
  rabbitmq_data:

services:

  #######################
  # Timer microservice
  #######################
  timer:
    build:
      context: ./Timer/
      dockerfile: Dockerfile
    image: esdg2t1/time:focustudy
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/timer
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

  #######################
  # Rating microservice
  #######################
  rating:
    build:
      context: ./Rating/
      dockerfile: Dockerfile
    image: esdg2t1/rating:focustudy
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/rating
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: focustudy-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
  
  ###################################
  # Error microservice
  ###################################
  error:
    build:
      context: ./Error/
      dockerfile: Dockerfile
    image: esdg2t1/error:focustudy
    restart: always
    # command: ["./wait-for-it.sh", "rabbitmq"] # testing spinning up rabbitMQ
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

  #########################################
  # Record Session complex microservice
  #########################################
  record_session:
    build:
      context: ./Record_Session/
      dockerfile: Dockerfile
    image: esdg2t1/record_session:focustudy
    restart: always
    # command: ["./wait-for-it.sh", "rabbitmq"] # testing spinning up rabbitMQ
    depends_on:
      - timer
      - rating
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      addTime_URL: http://timer:5002/addTime
      addRating_URL: http://rating:5001/addRating
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "5100:5100"
  
  #########################################
  # Display Session complex microservice
  #########################################
  display_sessions:
    build:
      context: ./Display_Sessions/
      dockerfile: Dockerfile
    image: 01371965/display_sessions:focustudy
    restart: always
    # command: ["./wait-for-it.sh", "rabbitmq"] # testing spinning up rabbitMQ
    depends_on:
      - timer
      - rating
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      displayTime_URL: http://timer:5002/getTimesAll
      displayRating_URL: http://rating:5001/getRatings
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "5200:5200"

  #######################
  # TaskList microservice
  #######################
  tasklist:
    build:
      context: ./TaskList/
      dockerfile: Dockerfile
    image: esdg2t1/tasklist:focustudy
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/tasklist
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "5000:5000"

  #######################
  # Spotify microservice
  #######################
  spotify:
    build:
      context: ./Spotify/
      dockerfile: Dockerfile
    image: esdg2t1/spotify:focustudy
    restart: always
    ports:
      - "5005:5005"

  ###################################
  # Activity Log microservice
  ###################################
  activity_log:
    build:
      context: ./ActivityLog/
      dockerfile: Dockerfile
    image: 01371965/activity_log:focustudy
    restart: always
    # command: ["./wait-for-it.sh", "rabbitmq"] # testing spinning up rabbitMQ
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1